# Generated by Django 5.2.3 on 2025-11-23 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('username', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatar/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('online_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
