# Generated by Django 5.2.3 on 2025-11-27 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Последний онлайн'),
        ),
    ]
