# Generated by Django 5.2.3 on 2025-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
